# Generated by Django 2.0.4 on 2018-04-29 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
