# Generated by Django 2.0.5 on 2018-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_auto_20180511_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='estado',
            field=models.NullBooleanField(),
        ),
    ]
