# Generated by Django 2.0.5 on 2018-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_auto_20180511_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='estado',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
